--ENTITY Genre--
--we don't need gcount in genre
CREATE TABLE  Genre (
  ID VARCHAR(20),
  name VARCHAR(300),
  PRIMARY KEY (ID)
  );

--ENTITY Artist--
CREATE TABLE  Artist (
  ID VARCHAR(20),
  name VARCHAR(200),
  type CHAR(10),
  gender CHAR(6),
  area_name VARCHAR(150),
  area_type VARCHAR(15),
  PRIMARY KEY (ID)
  );
  
--ENTITY Recording--
CREATE TABLE  recording (
  ID VARCHAR(20),
  name VARCHAR(2000),
  length VARCHAR(20),
  PRIMARY KEY (ID)
  );

--ENTITY RelaseMedium--
CREATE TABLE  ReleaseMedium (
  RID VARCHAR(20),
  MID VARCHAR(20),
  name VARCHAR(1000),
  format VARCHAR(45),
  PRIMARY KEY (MID)
  );

--ENTITY Track--
CREATE TABLE  Track (
  TID VARCHAR(20),
  RCID VARCHAR(20) NOT NULL,
  MID VARCHAR(20) NOT NULL,
  position INTEGER,
  PRIMARY KEY (TID),
  FOREIGN KEY (MID) REFERENCES ReleaseMedium,
  FOREIGN KEY (RCID) REFERENCES Recording
  );
    
--RELATIONSHIP artist_genre
CREATE TABLE artist_genre (
  AID VARCHAR(20) NOT NULL,
  GID VARCHAR(20) NOT NULL,
  PRIMARY KEY (AID, GID),
  FOREIGN KEY (AID) REFERENCES Artist ON DELETE CASCADE,
  FOREIGN KEY (GID) REFERENCES Genre ON DELETE CASCADE
  );
    
--RELATIONSHIP artist_track
CREATE TABLE artist_track(
  AID VARCHAR(20) NOT NULL,
  TID VARCHAR(20) NOT NULL,
  PRIMARY KEY (AID, TID),
  FOREIGN KEY (AID) REFERENCES Artist,
  FOREIGN KEY (TID) REFERENCES Track
  );

